### ISSUE TITLE
2.10.1，使用127.0.0.1访问时出现如下问题

### ISSUE THREAD

**Issue by Howard-Zhou-77** [ggg555ttt/MoeTalk#2]
<img width="1215" alt="image" src="https://github.com/ggg555ttt/MoeTalk/assets/67568722/e76733ec-dbba-49ff-b728-4f63cc5ded18">

控制台提示：
```
TypeError {}
message: "Cannot read properties of undefined (reading 'zh_cn')"
stack: "TypeError: Cannot read properties of undefined (reading 'zh_cn')\n at http://127.0.0.1/MoeScript/Mollu/index-1538eae7922ccaee.js?fgh:2077:23\n at Array.map (<anonymous>)\n at eb (http://127.0.0.1/MoeScript/Mollu/index-1538eae7922ccaee.js?fgh:2057:24)\n at ab (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:60857)\n at i (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:119415)\n at oO (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:99054)\n at http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:98921\n at oF (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:98928)\n at ox (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:95680)\n at oS (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:94235)"

A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    /MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:120770
Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:120770)
    at oO (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:99054)
    at http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:98921
    at oF (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:98928)
    at ox (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:95680)
    at oS (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:9:94235)
    at x (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:33:1373)
    at MessagePort.T (http://127.0.0.1/MoeScript/Mollu/framework-2c79e2a64abdb08b.js:33:1903)

Error rendering page: 
Error {}
Symbol(ASSET_LOAD_ERROR): undefined
message: "Failed to lookup route: /_error"
stack: "Error: Failed to lookup route: /_error\n at http://127.0.0.1/MoeScript/Mollu/main-dfffdc208236edda.js:1:34281"
__proto__: Error {}

O {code: "installations/request-failed...
code: "installations/request-failed"
customData: Object {requestName: "Create Installation",...
name: "FirebaseError"
message: "Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: API key not valid. Please pass a valid API key." (installations/request-failed)."
stack: "FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: API key not valid. Please pass a valid API key." (installations/request-failed).\n at ex (http://127.0.0.1/MoeScript/Mollu/_app-dc2c74db28f73016.js?fgh:10602:16)\n at async ej (http://127.0.0.1/MoeScript/Mollu/_app-dc2c74db28f73016.js?fgh:10687:12)\n at async eY (http://127.0.0.1/MoeScript/Mollu/_app-dc2c74db28f73016.js?fgh:10947:15)"
__proto__: O {}
```
使用`localhost`或使用局域网内查询到的本机IP可以正常加载页面。

**Comment by ggg555ttt** [comment]
具体原因我也不知道，好像以前有遇到过一次
现在用【127.0.01】或【localhost】都可以正常访问
个人怀疑是加速器或浏览器原因，但无法证实
